name: Send Images via Email

on:
  workflow_dispatch:

jobs:
  send_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Python script
        run: python3 send_images.py
